config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'application#index'

    resources :projects, only: [:new, :create, :destroy]
    resources :users do
      member do
        patch :archive
      end
    end
    resources :states, only: [:index, :new, :create] do
      member do
        get :make_default
      end
    end
  end

  devise_for :users

  root "projects#index"

  resources :projects, only: [:index, :show, :edit, :update] do
    resources :tickets
  end

  resources :tickets, only: [] do
    resources :comments, only: [:create]
  end

  resources :attachments, only: [:show, :new]
  

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :ticket

  mount_uploader :file, AttachmentUploader
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :ticket
  belongs_to :previous_state, class_name: "State"
  belongs_to :state
  belongs_to :author, class_name: "User"

  scope :persisted, lambda { where.not(id: nil) }
  
  validates :text, presence: true

  delegate :project, to: :ticket

  before_create :set_previous_state
  after_create :set_ticket_state

  private 

  def set_previous_state
    self.previous_state = ticket.state
  end

  def set_ticket_state
  	ticket.state = state
  	ticket.save!
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
	
	has_many :tickets, dependent: :delete_all
	has_many :roles, dependent: :delete_all
	
	validates :name, presence: true

	def has_member?(user)
		roles.exists?(user_id: user)
	end

	[:manager, :editor, :viewer].each do |role|
		define_method "has_#{role}?" do |user|
			roles.exists?(user_id: user, role: role)
		end
	end
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  def self.available_roles
  	%w(manager editor viewer)
  end
end

app/models/state.rb
class State < ActiveRecord::Base
	def self.default
		find_by(default: true)
	end 
	
	def make_default!
		State.update_all(default: false)
		update!(default: true)
	end
	
	def to_s
		name
	end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  belongs_to :author, class_name: "User"
  belongs_to :state
  has_many :attachments, dependent: :destroy
  has_many :comments, dependent: :destroy

  accepts_nested_attributes_for :attachments, reject_if: :all_blank

  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 10 }

  before_create :assign_default_state

  private

  def assign_default_state
  	self.state ||= State.default
  end
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :roles
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable

    scope :excluding_archived, lambda { where(archived_at: nil) }

    def to_s
    	"#{email} (#{admin? ? "Admin" : "User"})"
    end

    def archive
    	self.update(archived_at: Time.now)
    end

    def active_for_authentication?
    	super && archived_at.nil?
    end

    def inactive_message
    	archived_at.nil? ? super : :archived
    end

    def role_on(project)
        roles.find_by(project_id: project).try(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include Pundit

	after_action :verify_authorized, except: [:index],
		unless: :devise_controller?
	after_action :verify_policy_scoped, only: [:index],
		unless: :devise_controller?
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception

	rescue_from Pundit::NotAuthorizedError, with: :not_authorized

	private 

	def not_authorized
		redirect_to root_path, alert: "You aren't allowed to do that."
	end
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
	skip_after_action :verify_authorized, only: [:new]
	
	def show
		attachment = Attachment.find(params[:id])
		authorize attachment, :show?
		send_file attachment.file.path, disposition: :inline
	end

	def new
		@index = params[:index].to_i
		@ticket = Ticket.new
		@ticket.attachments.build
		render layout: false
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_ticket

	def create
		whitelisted_params = comment_params

		unless policy(@ticket).change_state?
			whitelisted_params.delete(:state_id)
		end

		@comment = @ticket.comments.build(whitelisted_params)
		@comment.author = current_user
		authorize @comment, :create?

		if @comment.save
			flash[:notice] = "Comment has been created."
			redirect_to [@ticket.project, @ticket]
		else
			flash.now[:alert] = "Comment has not been created."
			@project = @ticket.project
			render "tickets/show"
		end
	end

	private 

	def set_ticket
		@ticket = Ticket.find(params[:ticket_id])
	end
	
	def comment_params
		params.require(:comment).permit(:text, :state_id)
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :set_project, only: [:show, :edit, :update]

	def index
		@projects = policy_scope(Project)
	end

	def show
		authorize @project, :show?
	end

	def edit
		authorize @project, :update?
	end

	def update
		authorize @project, :update?
		
		if @project.update(project_params)
			flash[:notice] = "Project has been updated."
			redirect_to @project
		else
			flash.now[:alert] = "Project has not been updated."
			render "edit"
		end
	end

	private
		def set_project
			@project = Project.find(params[:id])
		rescue ActiveRecord::RecordNotFound
			flash[:alert] = "The project you were looking for could not be found."
			redirect_to projects_path
		end

		def project_params
			params.require(:project).permit(:name, :description)
		end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
	before_action :set_project
	before_action :set_ticket, only: [:show, :edit, :update, :destroy]

	def show
		authorize @ticket, :show?
		@comment = @ticket.comments.build(state_id: @ticket.state_id)
	end

	def new
		@ticket = @project.tickets.build
		authorize @ticket, :create?
		@ticket.attachments.build
	end

	def create
		@ticket = @project.tickets.build(ticket_params)
		@ticket.author = current_user
		authorize @ticket, :create?
		
		if @ticket.save
			flash[:notice] = "Ticket has been created."
			redirect_to [@project, @ticket]
		else
			flash.now[:alert] = "Ticket has not been created."
			render "new"
		end
	end

	def edit
		authorize @ticket, :update?
	end

	def update
		authorize @ticket, :update?
		
		if @ticket.update(ticket_params)
			flash[:notice] = "Ticket has been updated."
			redirect_to [@project, @ticket]
		else
			flash[:alert] = "Ticket has not been updated."
			render "new"
		end
	end

	def destroy
		authorize @ticket, :destroy?
		
		@ticket.destroy
		flash[:notice] = "Ticket has been deleted."

		redirect_to @project
	end

	private
		def set_project
			@project = Project.find(params[:project_id])
		end

		def set_ticket 
			@ticket = @project.tickets.find(params[:id])
		end

		def ticket_params
			params.require(:ticket).permit(:name, :description, 
				attachments_attributes: [:file, :file_cache])
		end
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/admin/states_helper.rb
module Admin::StatesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title(*parts)
		unless parts.empty?
			content_for :title do
				(parts << "Ticketee").join(" - ")
			end
		end
	end

	def admins_only(&block)
		block.call if current_user.try(:admin?)
	end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
	def state_transition_for(comment)
		if comment.previous_state != comment.state
			content_tag(:p) do
				value = "<strong><i class='fa fa-gear'></i> state changed</strong>"
				if comment.previous_state.present?
					value += "from #{render comment.previous_state}"
				end
				value += " to #{render comment.state}"
				value.html_safe
			end
		end
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
  	<% if content_for?(:title) %>
  		<%= yield(:title) %>
  	<% else %>
  		Ticketee
  	<% end %>
  </title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <style>
    <% State.all.each do |state| %>
      .state-<%= state.name.parameterize %> {
        background-color: <%= state.color %>
      }
    <% end %>
  </style>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Ticketee", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= "active" if current_page?("/") %>">
          <%= link_to "Home", root_path %>
        </li>
        <% unless user_signed_in? %>
          <li class="<%= "active" if current_page?("/users/sign_up") %>">
            <%= link_to "Sign Up", new_user_registration_path %>
          </li>
          <li class="<%= "active" if current_page?("/users/sign_in") %>">
            <%= link_to "Sign In", new_user_session_path %>
          </li>
        <% end %>

        <% admins_only do %>
          <li><%= link_to "Admin", admin_root_path %></li>
        <% end %>
        <% if user_signed_in? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <p class="navbar-text">
            Signed in as <%= current_user.email %>
          </p>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

<div class="container">
  <% flash.each do |key, message| %>
  	<div class="alert alert-<%= key %>">
      <%= message %>
    </div>
  <% end %>

  <%= yield %>
</div>

</body>
</html>